# Generated by Django 4.2.2 on 2024-10-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='359507316115', max_length=15, verbose_name='код из письма'),
        ),
    ]
