# Generated by Django 4.2.2 on 2024-10-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('view_all_clients', 'Может просматривать всех клиентов'), ('block_client', 'Может блокировать клиентов')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['name'], 'permissions': [('view_all_mailings', 'Может просматривать все рассылки'), ('disable_mailing', 'Может отключать рассылки')], 'verbose_name': 'письмо', 'verbose_name_plural': 'письма'},
        ),
    ]
